apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: checkout-now
  labels:
    app: backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
      - name: backend
        image: checkout-backend:latest
        imagePullPolicy: Never  # For local k3s development
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: checkout-app-config
              key: SERVER_PORT
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: checkout-app-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: checkout-app-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: checkout-app-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: checkout-app-secrets
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: checkout-app-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        - name: SPRING_JPA_DATABASE_PLATFORM
          valueFrom:
            configMapKeyRef:
              name: checkout-app-config
              key: SPRING_JPA_DATABASE_PLATFORM
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: checkout-app-secrets
              key: JWT_SECRET
        - name: EMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: checkout-app-secrets
              key: EMAIL_USERNAME
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: checkout-app-secrets
              key: EMAIL_PASS
        - name: TWILIO_SID
          valueFrom:
            secretKeyRef:
              name: checkout-app-secrets
              key: TWILIO_SID
        - name: TWILIO_TOKEN
          valueFrom:
            secretKeyRef:
              name: checkout-app-secrets
              key: TWILIO_TOKEN
        - name: WHATSAPP_NUMBER
          valueFrom:
            secretKeyRef:
              name: checkout-app-secrets
              key: WHATSAPP_NUMBER
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: checkout-now
  labels:
    app: backend
    tier: backend
spec:
  selector:
    app: backend
    tier: backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP